### ISSUE TITLE
[AdminApp] Ability to Create custom filters from WebApp

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-webapp#86]
Org Admin should be able to create custom filters and store json on organisation_config table.
Ability to specify dashboard and search filters.

{
  "languages": [
    "en",
    "gu_IN"
  ],
  "myDashboardFilters": [
    {
      "titleKey": "Standard",
      "conceptUUID": "fda18675-59dc-4a69-82f7-4e137c274073",
      "searchType": "programEncounter",
      "searchParameters": {
        "encounterTypeUUID": "14e23e16-5db0-4d16-9efe-b206a18010a7",
        "programUUID": "215f4795-7d46-4617-95dd-52343f945a0f"
      }
    },
    {
      "titleKey": "Sickness in last 3 month",
      "conceptUUID": "49b70138-ea65-45ee-8f3f-676bb8a1f8d3",
      "searchType": "programEncounter",
      "searchParameters": {
        "encounterTypeUUID": "198b4844-2c66-4ad2-9a9c-3099270695a4",
        "programUUID": "215f4795-7d46-4617-95dd-52343f945a0f"
      }
    },
    {
      "titleKey": "Have difficulty in breathing",
      "conceptUUID": "bc1e3b8e-5ecf-4ac4-8058-9a1e228b0304",
      "searchType": "programEnrolment",
      "searchParameters": {
        "programUUID": "215f4795-7d46-4617-95dd-52343f945a0f"
      }
    },
    {
      "titleKey": "Block",
      "conceptUUID": "87e1989a-c690-4385-b3da-e6e1bacc8f85",
      "searchType": "registration"
    }
  ],
  "searchFilters": [
    {
      "titleKey": "Standard",
      "conceptUUID": "fda18675-59dc-4a69-82f7-4e137c274073",
      "searchType": "programEncounter",
      "searchParameters": {
        "encounterTypeUUID": "14e23e16-5db0-4d16-9efe-b206a18010a7",
        "programUUID": "215f4795-7d46-4617-95dd-52343f945a0f"
      }
    }
  ]
}

**Comment by garimadosar5** [comment]
![Screen Shot 2019-10-24 at 3.13.37 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3c3493ad-604d-4b8c-a445-a8c24bb0405a)

**Comment by vindeolal** [comment]
@garimadosar5 
Concept issue is fixed.
For me UI is showing properly. Can check once again.

**Comment by garimadosar5** [comment]
@vindeolal 

UI is the same concept issue is also not fixed. Did you deploy the changes on staging?
